name: Deploy to DigitalOcean Kubernetes
on:
  push:
    branches:
      - main 
    paths:
      - 'games/**'
      - '.github/workflows/deploy-games.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout master
      uses: actions/checkout@main
    
    - name: Install doctl
      uses: digitalocean/action-doctl@v2
      with:
        token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

    - name: Save DigitalOcean kubeconfig with short-lived credentials
      run: doctl kubernetes cluster kubeconfig save --expiry-seconds 600 ${{ secrets.CLUSTER_NAME }}

    - name: Deploy to DigitalOcean Kubernetes
      run: kubectl apply -f $GITHUB_WORKSPACE/games/deployment.yml -n games

    - name: Verify deployment
      run: kubectl rollout status deployment/mario-deployment -n games